console.log("showContent");
title = document.currentScript.getAttribute("title");
description = document.currentScript.getAttribute("description");
img_url = document.currentScript.getAttribute("img_url");
a_href = document.currentScript.getAttribute("a_href");
console.log(title);
console.log(description);
console.log(img_url);
console.log(a_href);
var template = document.querySelector("template");
var img = template.content.querySelector("img");
var h4 = template.content.querySelector("h4");
var p = template.content.querySelector("p");
var a = template.content.querySelector("a");
h4.innerHTML = title;
p.innerHTML = description;
img.src = img_url;
a.href = a_href;
var node = document.importNode(template.content, true);
console.log(node);
document.getElementsByClassName("main_container")[0].appendChild(node);
document.body.appendChild(node);
