theme: jekyll-theme-cayman

title: [My Data Science Notes]
description: [I am sharing my notes from difference source here]
show_downloads: ["true"]
#google_analytics: [Your Google Analytics tracking ID]
